declare enum ECardType {
    ENCHANTMENT = "ENCHANTMENT",
    GAME_MODE_BUTTON = "GAME_MODE_BUTTON",
    HERO = "HERO",
    HERO_POWER = "HERO_POWER",
    LETTUCE_ABILITY = "LETTUCE_ABILITY",
    MINION = "MINION",
    MOVE_MINION_HOVER_TARGET = "MOVE_MINION_HOVER_TARGET",
    SPELL = "SPELL",
    WEAPON = "WEAPON"
}
export default ECardType;
