"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ECardClass;
(function (ECardClass) {
    ECardClass["DEATHKNIGHT"] = "DEATHKNIGHT";
    ECardClass["DEMONHUNTER"] = "DEMONHUNTER";
    ECardClass["DREAM"] = "DREAM";
    ECardClass["DRUID"] = "DRUID";
    ECardClass["HUNTER"] = "HUNTER";
    ECardClass["MAGE"] = "MAGE";
    ECardClass["NEUTRAL"] = "NEUTRAL";
    ECardClass["PALADIN"] = "PALADIN";
    ECardClass["PRIEST"] = "PRIEST";
    ECardClass["ROGUE"] = "ROGUE";
    ECardClass["SHAMAN"] = "SHAMAN";
    ECardClass["WARLOCK"] = "WARLOCK";
    ECardClass["WARRIOR"] = "WARRIOR";
    ECardClass["WHIZBANG"] = "WHIZBANG";
})(ECardClass || (ECardClass = {}));
exports.default = ECardClass;
