"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ECardSet;
(function (ECardSet) {
    ECardSet["BATTLEGROUNDS"] = "BATTLEGROUNDS";
    ECardSet["BLACK_TEMPLE"] = "BLACK_TEMPLE";
    ECardSet["BOOMSDAY"] = "BOOMSDAY";
    ECardSet["BRM"] = "BRM";
    ECardSet["CORE"] = "CORE";
    ECardSet["CREDITS"] = "CREDITS";
    ECardSet["DALARAN"] = "DALARAN";
    ECardSet["DARKMOON_FAIRE"] = "DARKMOON_FAIRE";
    ECardSet["DEMON_HUNTER_INITIATE"] = "DEMON_HUNTER_INITIATE";
    ECardSet["DRAGONS"] = "DRAGONS";
    ECardSet["EXPERT1"] = "EXPERT1";
    ECardSet["GANGS"] = "GANGS";
    ECardSet["GILNEAS"] = "GILNEAS";
    ECardSet["GVG"] = "GVG";
    ECardSet["HERO_SKINS"] = "HERO_SKINS";
    ECardSet["HOF"] = "HOF";
    ECardSet["ICECROWN"] = "ICECROWN";
    ECardSet["KARA"] = "KARA";
    ECardSet["LEGACY"] = "LEGACY";
    ECardSet["LETTUCE"] = "LETTUCE";
    ECardSet["LOE"] = "LOE";
    ECardSet["LOOTAPALOOZA"] = "LOOTAPALOOZA";
    ECardSet["MISSIONS"] = "MISSIONS";
    ECardSet["NAXX"] = "NAXX";
    ECardSet["OG"] = "OG";
    ECardSet["SCHOLOMANCE"] = "SCHOLOMANCE";
    ECardSet["STORMWIND"] = "STORMWIND";
    ECardSet["TAVERNS_OF_TIME"] = "TAVERNS_OF_TIME";
    ECardSet["TB"] = "TB";
    ECardSet["TGT"] = "TGT";
    ECardSet["THE_BARRENS"] = "THE_BARRENS";
    ECardSet["TROLL"] = "TROLL";
    ECardSet["ULDUM"] = "ULDUM";
    ECardSet["UNGORO"] = "UNGORO";
    ECardSet["VANILLA"] = "VANILLA";
    ECardSet["YEAR_OF_THE_DRAGON"] = "YEAR_OF_THE_DRAGON";
})(ECardSet || (ECardSet = {}));
exports.default = ECardSet;
